### ISSUE TITLE
Problem in toJSON and fromJSON with Model

### ISSUE THREAD

**Issue by aviadkam** [dart-ogurets/dart-openapi-maven#72]
in the **toJSON** function, in the case of is Model, the template will run isModel and isAnyType. so the value `json[r'{{baseName}}'] = {{{name}}};` can be found twice in the generated code.
Need to add ^isModel when running isAnyType. 

in case of **fromJSON**, in case of isModel, the generated code returns only the `json[r'{{{name}}}']` instead of `(json[r'{{{name}}}'] == null) ? null : {{{complexType}}}.fromJson(json[r'{{{name}}}']);`

plus, in the comparator == it is a good practice to add this.{{{name}}} before comparing

Happens only while running with `openapi-generator-cli-5.3.0.jar`

**Comment by rvowles** [comment]
This is specifically an issue introduced in 5.3 - the OpenAPI code base appears to be incorrectly categorising Any types as models as well. The decision I have discussed with @aviadkam is to fix it in the code rather than change the mustache templates, but people can use 5.2.1 in the meantime. 

Appreciate the heads up on the issue in 5.3!

**Comment by rvowles** [comment]
Hey @aviadkam - do you have a sample bit of OpenAPI YAML that can recreate this please? None of my existing testing yaml is causing the break and I'd like to have a chunk of an API that cause the breakage :-)
